package aws

const (
	S3_STORAGE_CLASS_STANDARD            = "STANDARD"
	S3_STORAGE_CLASS_REDUCED_REDUNDANCY  = "REDUCED_REDUNDANCY"
	S3_STORAGE_CLASS_GLACIER             = "GLACIER"
	S3_STORAGE_CLASS_STANDARD_IA         = "STANDARD_IA"
	S3_STORAGE_CLASS_INTELLIGENT_TIERING = "INTELLIGENT_TIERING"
	S3_STORAGE_CLASS_DEEP_ARCHIVE        = "DEEP_ARCHIVE"
	S3_STORAGE_CLASS_GLACIER_IR          = "GLACIER_IR"

	REGION_CST = "region"
)
