package aws

var (
	StorageClassesSKU = []string{
		S3_SKU_VOL_STANDARD,
		S3_SKU_VOL_STANDARD_INFREQUENT_ACCESS,
		S3_SKU_VOL_REDUCED_REDUNDANCY,
		S3_SKU_VOL_INTELLIGENT_TIERING_ARCHIVE_INSTANT_ACCESS,
		S3_SKU_VOL_INTELLIGENT_TIERING_ARCHIVE_ACCESS,
		S3_SKU_VOL_INTELLIGENT_TIERING_INFREQUENT_ACCESS,
		S3_SKU_VOL_INTELLIGENT_TIERING_DEEP_ARCHIVE_ACCESS,
		S3_SKU_VOL_INTELLIGENT_TIERING_FREQUENT_ACCESS,
		S3_SKU_VOL_AMAZON_GLACIER,
		S3_SKU_VOL_AMAZON_GLACIER_STAGING,
		S3_SKU_VOL_GLACIER_DEEP_ARCHIVE,
		S3_SKU_VOL_GLACIER_INSTANT_RETRIEVAL,
		S3_SKU_VOL_ONE_ZONE_INFREQUENT_ACCESS}
)

const (
	S3_SKU_VOL_STANDARD                                   = "9MDYGCA9S4SXXTJF"
	S3_SKU_VOL_STANDARD_INFREQUENT_ACCESS                 = "EEADMYR3YTRCD3AM"
	S3_SKU_VOL_REDUCED_REDUNDANCY                         = "KSN9K5R3E3KA9P37"
	S3_SKU_VOL_INTELLIGENT_TIERING_ARCHIVE_INSTANT_ACCESS = "MNVNKQFVJ2RC25V5"
	S3_SKU_VOL_INTELLIGENT_TIERING_ARCHIVE_ACCESS         = "ZMMBXYXEAVRBUZNA"
	S3_SKU_VOL_INTELLIGENT_TIERING_INFREQUENT_ACCESS      = "TF3CZY44ATXA7H4U"
	S3_SKU_VOL_INTELLIGENT_TIERING_DEEP_ARCHIVE_ACCESS    = "QFXSVY32P5GDU8N6"
	S3_SKU_VOL_INTELLIGENT_TIERING_FREQUENT_ACCESS        = "X46QDPG7T8HTN57T"
	S3_SKU_VOL_AMAZON_GLACIER                             = "FPVXA3S73QBD73EV"
	S3_SKU_VOL_AMAZON_GLACIER_STAGING                     = "USUKP5XG3Q5ZSH7S"
	S3_SKU_VOL_GLACIER_DEEP_ARCHIVE                       = "Y9VY97QSKVYBC8M5"
	S3_SKU_VOL_GLACIER_INSTANT_RETRIEVAL                  = "6QFU56EDTKT8CGPH"
	S3_SKU_VOL_ONE_ZONE_INFREQUENT_ACCESS                 = "TX2PVYSPAP4RJAS9"

	REGION_CST = "region"
)
